"""add risk prediction fields

Revision ID: add_risk_fields
Revises: 9cbc11040b5c
Create Date: 2026-05-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_risk_fields'
down_revision: Union[str, None] = '9cbc11040b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_logs', sa.Column('completion_risk_probability', sa.Float(), nullable=True))
    op.add_column('match_logs', sa.Column('risk_factors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_logs', 'risk_factors')
    op.drop_column('match_logs', 'completion_risk_probability')
    # ### end Alembic commands ###